# ID is set to 'BasinEngi' as 'BasinTech' will break the loadout screen for whatever reason. -Cookie
- type: job
  id: BasinEngi
  name: job-name-basintech
  description: job-description-basintech
  playTimeTracker: JobBasinTech
  requirements:
    - !type:DepartmentTimeRequirement
     department: Cargo
     time: 3600 # 1 hr
  icon: "JobIconShaftMiner"
  startingGear: PilotGear_2
  supervisors: job-supervisors-qm
  access:
  - Salvage
  - Maintenance
  - External

- type: startingGear
  id: PilotGear_2
  equipment:
    jumpsuit: ClothingUniformJumpsuitSalvageSpecialist
    id: BasinTechPDA
    ears: ClothingHeadsetCargo
    eyes: ClothingEyesGlassesMeson
    gloves: ClothingHandsGlovesColorYellow
    shoes: ClothingShoesBootsSalvage
    back: ClothingBackpackSatchelLeather
    belt: ClothingBeltUtilityEngineering

- type: roleLoadout
  id: JobBasinEngi
  groups:
  - GroupTankHarness
  - SalvageSpecialistBackpack
  - SalvageSpecialistOuterClothing
  - SalvageSpecialistShoes
  - Glasses
  - Survival
  - Trinkets
  - GroupSpeciesBreathTool

