- type: job
  id: Passenger
  name: job-name-passenger
  description: job-description-passenger
  playTimeTracker: JobPassenger
  startingGear: PassengerGear
  icon: "JobIconPassenger"
  supervisors: job-supervisors-everyone
  access:
  - Maintenance

- type: startingGear
  id: PassengerGear
  equipment:
    id: PassengerPDA
    ears: ClothingHeadsetGrey
    shoes: ClothingShoesLeather
    outerClothing: ClothingOuterCoatBomber
    jumpsuit: ClothingUniformJumpsuitLoungewear
  #storage:
    #back:
    #- Stuff
